# import = ["~/.config/alacritty/themes/gruvbox-dark.toml"] 

[font]
size = 13  # Adjust font size to your liking

[font.normal]
family = "JetBrainsMono Nerd Font"  # Replace with your preferred font
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"  # Replace with your preferred font
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"  # Replace with your preferred font
style = "Italic"

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both" # to use the option key as alt on mac os x

