[font]
size = 13  # Adjust font size to your liking

[font.normal]
family = "JetBrainsMono Nerd Font"  # Replace with your preferred font
style = "Book"


[font.bold]
family = "JetBrainsMono Nerd Font"  # Replace with your preferred font
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"  # Replace with your preferred font
style = "Italic"

[env]
TERM = "xterm-256color"

