tap "homebrew/bundle"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Render markdown on the CLI
brew "glow"
# Improved top (interactive process viewer)
brew "htop"
# Extraction utility for .zip compressed archives
brew "unzip"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Lazier way to manage everything docker
brew "lazydocker"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Programmatically correct mistyped console commands
brew "thefuck"
# Shell extension to navigate your filesystem faster
brew "zoxide"
vscode "4ops.terraform"
vscode "alefragnani.bookmarks"
vscode "blinkshellinc.blink-fs"
vscode "bmewburn.vscode-intelephense-client"
vscode "damc.geal-theme"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "emeraldwalk.runonsave"
vscode "equinusocio.vsc-material-theme-icons"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "harryhopkinson.vim-theme"
vscode "hashicorp.hcl"
vscode "hashicorp.terraform"
vscode "humao.rest-client"
vscode "jdinhlife.gruvbox"
vscode "lkrms.inifmt"
vscode "mechatroner.rainbow-csv"
vscode "mehedidracula.php-namespace-resolver"
vscode "mkloubert.vscode-http-client"
vscode "monokai.theme-monokai-pro-vscode"
vscode "mquandalle.graphql"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azureterraform"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.dotnet-interactive-vscode"
vscode "ms-dotnettools.vscode-dotnet-pack"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vscode.sublime-keybindings"
vscode "ms-vscode.vs-keybindings"
vscode "ms-vscode.vscode-typescript-next"
vscode "octref.vetur"
vscode "p1c2u.docker-compose"
vscode "pkief.material-icon-theme"
vscode "pmneo.tsimporter"
vscode "randomfractalsinc.vscode-data-preview"
vscode "redhat.vscode-yaml"
vscode "rokoroku.vscode-theme-darcula"
vscode "seltonfiuza.terragrunt-easy-plan"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "vscodevim.vim"
vscode "vue.volar"
vscode "wayou.vscode-todo-highlight"
